### ISSUE TITLE
Transport Clerk

### ISSUE THREAD

**Issue by hartdylan** [AugustanaCSC285Fall17/CurlewRepo#60]
Upon proceeding to the slide "Transport Clerk", I have become stuck without any option to go to a new 'slide' or room. But I still have the functionality to use the menu buttons in the top left.

**Comment by minhta16** [comment]
Can you describe more of your choices if possible? Maybe about your gender, your letter, money you have left etc...

**Comment by hartdylan** [comment]
I can't recall what my choices were except I know that I was Anders.
