### ISSUE TITLE
Just A suggestion about the Magnifying feature. 

### ISSUE THREAD

**Issue by LunaDefender** [AugustanaCSC285Fall17/CurlewRepo#61]
I really like the magnifying feature but the box where you can zoom seems really big. Is there a way you could make that box small? It leaves a lot of white space.

**Comment by minhta16** [comment]
The picture is formatted in a way that every image is a square shape of a same size so that implementing them is easier. However, I am going to add a pair of magnifying function buttons (to inc. and dec. zooming size)
