### ISSUE TITLE
Alcoholic Drink

### ISSUE THREAD

**Issue by hartdylan** [AugustanaCSC285Fall17/CurlewRepo#62]
On the slide "Alcoholic Drink" you are given two options to proceed further but when clicking "sneak past the conductor" you are taken to a new slide but the new slide will reset you to the beginning to the "Anders Bengtsson" slide and it also states that you lose your luggage but you still have any letter contents in your inventory.

**Comment by minhta16** [comment]
Thanks! Bug fixed.
